# Topic Modeling

## Introduction

Another popular text analysis technique is called topic modeling. The ultimate goal of topic modeling is to find various topics that are present in your corpus. Each document in the corpus will be made up of at least one topic, if not multiple topics.

In this notebook, we will be covering the steps on how to do **Latent Dirichlet Allocation (LDA)**, which is one of many topic modeling techniques. It was specifically designed for text data.

To use a topic modeling technique, you need to provide (1) a document-term matrix and (2) the number of topics you would like the algorithm to pick up.

Once the topic modeling technique is applied, your job as a human is to interpret the results and see if the mix of words in each topic make sense. If they don't make sense, you can try changing up the number of topics, the terms in the document-term matrix, model parameters, or even try a different model.

## Topic Modeling - Attempt #1 (All Text)

In [1]:
# Let's read in our document-term matrix
import pandas as pd
import pickle

data = pd.read_pickle('dtm_stop.pkl')
data

,aaaaaa,aaaaaah,aaaaah,aaah,aah,abandon,abandoned,abc,abcs,abetter,...,zillion,ziploc,zoloft,zombie,zombies,zoning,zoo,zoom,zuko,éclair
ali,0,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bill,0,0,1,0,0,0,0,0,1,0,...,1,0,0,1,1,1,0,0,0,0
dave,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
eric,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
george,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
kenny,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
louis,0,0,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pete,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
taylor,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
tom,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
trevor,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
whitney,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [2]:
# Import the necessary modules for LDA with gensim
# Terminal / Anaconda Navigator: conda install -c conda-forge gensim
from gensim import matutils, models
import scipy.sparse

# import logging
# logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

In [3]:
# One of the required inputs is a term-document matrix
tdm = data.transpose()
tdm.head()

,ali,anthony,bill,dave,eric,george,jim,joe,john,kenny,louis,mike,pete,ricky,taylor,tom,trevor,whitney
aaaaaa,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0
aaaaaah,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
aaaaah,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
aaah,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
aah,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0

In [4]:
# We're going to put the term-document matrix into a new gensim format, from df --> sparse matrix --> gensim corpus
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

In [5]:
# Gensim also requires dictionary of the all terms and their respective location in the term-document matrix
cv = pickle.load(open("cv_stop.pkl", "rb"))
id2word = dict((v, k) for k, v in cv.vocabulary_.items())

Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term), we need to specify two other parameters - the number of topics and the number of passes. Let's start the number of topics at 2, see if the results make sense, and increase the number from there.

In [28]:
# Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term),
# we need to specify two other parameters as well - the number of topics and the number of passes
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=2, passes=10)
lda.print_topics()

[(0,
  '0.009*"fucking" + 0.005*"went" + 0.005*"fuck" + 0.004*"theres" + 0.004*"life" + 0.004*"ive" + 0.004*"come" + 0.004*"okay" + 0.004*"ill" + 0.004*"man"'),
 (1,
  '0.005*"man" + 0.005*"guys" + 0.004*"okay" + 0.004*"make" + 0.004*"look" + 0.004*"kids" + 0.003*"way" + 0.003*"come" + 0.003*"theres" + 0.003*"hey"')]

In [29]:
# LDA for num_topics = 3
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=3, passes=10)
lda.print_topics()

[(0,
  '0.008*"fucking" + 0.004*"went" + 0.004*"man" + 0.004*"fuck" + 0.004*"theres" + 0.004*"life" + 0.004*"come" + 0.004*"way" + 0.004*"look" + 0.004*"kids"'),
 (1,
  '0.006*"okay" + 0.005*"guys" + 0.005*"man" + 0.004*"make" + 0.004*"theres" + 0.004*"went" + 0.004*"come" + 0.004*"ive" + 0.003*"ill" + 0.003*"life"'),
 (2,
  '0.004*"ok" + 0.004*"lot" + 0.004*"wanna" + 0.004*"gotta" + 0.003*"husband" + 0.003*"women" + 0.003*"pregnant" + 0.002*"need" + 0.002*"god" + 0.002*"tell"')]

In [8]:
# LDA for num_topics = 4
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=4, passes=10)
lda.print_topics()

[(0,
  '0.011*"fucking" + 0.006*"man" + 0.005*"went" + 0.005*"fuck" + 0.004*"okay" + 0.004*"come" + 0.004*"ill" + 0.004*"theres" + 0.004*"ive" + 0.003*"big"'),
 (1,
  '0.006*"guys" + 0.005*"make" + 0.004*"look" + 0.004*"kids" + 0.004*"okay" + 0.004*"way" + 0.004*"feel" + 0.004*"man" + 0.004*"tell" + 0.004*"shes"'),
 (2,
  '0.005*"life" + 0.004*"guys" + 0.004*"theres" + 0.004*"okay" + 0.004*"lot" + 0.004*"way" + 0.004*"mom" + 0.004*"shes" + 0.004*"tell" + 0.004*"man"'),
 (3,
  '0.011*"fucking" + 0.005*"id" + 0.005*"went" + 0.005*"fuck" + 0.004*"theres" + 0.004*"come" + 0.004*"years" + 0.004*"make" + 0.004*"dude" + 0.004*"ill"')]

These topics aren't looking too great. We've tried modifying our parameters. Let's try modifying our terms list as well.

## Topic Modeling - Attempt #2 (Nouns Only)

One popular trick is to look only at terms that are from one part of speech (only nouns, only adjectives, etc.). Check out the UPenn tag set: https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html.

In [9]:
# Let's create a function to pull out nouns from a string of text
from nltk import word_tokenize, pos_tag

def nouns(text):
    '''Given a string of text, tokenize the text and pull out only the nouns.'''
    is_noun = lambda pos: pos[:2] == 'NN'
    tokenized = word_tokenize(text)
    all_nouns = [word for (word, pos) in pos_tag(tokenized) if is_noun(pos)] 
    return ' '.join(all_nouns)

In [10]:
# Read in the cleaned data, before the CountVectorizer step
data_clean = pd.read_pickle('data_clean.pkl')
data_clean

                                                transcript
ali      ladies and gentlemen please welcome to the sta...
anthony  thank you thank you thank you san francisco th...
bill      all right thank you thank you very much thank...
dave     whats in a name is a  talk chappelle delivered...
eric     opening sketch                   i stole this ...
george   recorded on november   beacon theater new york...
jim         ladies and gentlemen please welcome to the ...
joe         ladies and gentlemen welcome joe rogan  wha...
john     armed with boyish charm and a sharp wit the fo...
kenny    make some noise for kenny sebastian oh my god ...
louis    introfade the music out lets roll hold there l...
mike     wow hey thank you thanks thank you guys hey se...
pete     ♪ old lady on my case again ♪ ♪ told me straig...
ricky    hello hello how you doing great thank you wow ...
taylor      please welcome taylor tomlinson  thank you ...
tom      ♪ now the time is right ♪ ♪ bright city light ...
trevor    potatoeszah zah potatoes baby  baby  baby  ca...
whitney     give it up for my good friend and yours whi...

In [11]:
# Apply the nouns function to the transcripts to filter only on nouns
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
data_nouns = pd.DataFrame(data_clean.transcript.apply(nouns))
data_nouns

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

                                                transcript
ali      ladies gentlemen stage ali hi thank hello na s...
anthony  thank thank people i em i francisco city world...
bill     thank thank pleasure georgia area oasis i june...
dave     whats name talk chappelle school arts washingt...
eric     sketch i evidence room man damn fool mushrooms...
george   beacon theater york city york man thank man ma...
jim      ladies gentlemen stage mr jim jefferies thank ...
joe      ladies gentlemen joe fck thanks phone fckface ...
john     charm wit snl writer john mulaney marriage bee...
kenny    noise oh god thank mumbai thank lets guys roya...
louis    music lets lights lights thank i i place place...
mike     wow hey thanks look insane years everyone i id...
pete     lady case ♪ ♪ shirt ♪ ♪ i win ♪ ♪ fuck crib sp...
ricky    hello thank fuck thank im gon youre weve money...
taylor   taylor tomlinson thank thank couple years bang...
tom      time ♪ ♪ city light ♪ ♪ turn louder ♪ ♪ name ♪...
trevor   potatoeszah zah potatoes baby house yep yep ye...
whitney  friend whitney cummings jersey whoo thank i mi...

In [12]:
# Create a new document-term matrix using only nouns
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

# Re-add the additional stop words since we are recreating the document-term matrix
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people',
                  'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)

# Recreate a document-term matrix with only nouns
cvn = CountVectorizer(stop_words=stop_words)
data_cvn = cvn.fit_transform(data_nouns.transcript)
data_dtmn = pd.DataFrame(data_cvn.toarray(), columns=cvn.get_feature_names())
data_dtmn.index = data_nouns.index
data_dtmn

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aaaaaa,aaaaaah,aaah,aah,abc,abcs,ability,abortion,abraham,abuse,...,zebulon,zeppelin,zero,zillion,ziploc,zombie,zombies,zoo,zoom,éclair
ali,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
anthony,0,0,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
bill,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,1,1,0,0,0
dave,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
eric,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
george,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
kenny,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
louis,0,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
pete,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ricky,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
taylor,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
tom,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
trevor,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
whitney,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
# Create the gensim corpus
corpusn = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

# Create the vocabulary dictionary
id2wordn = dict((v, k) for k, v in cvn.vocabulary_.items())

In [14]:
# Let's start with 2 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=2, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.009*"man" + 0.008*"kids" + 0.008*"day" + 0.007*"guy" + 0.007*"thing" + 0.006*"way" + 0.006*"cause" + 0.006*"things" + 0.006*"shit" + 0.005*"theyre"'),
 (1,
  '0.010*"thing" + 0.009*"day" + 0.008*"hes" + 0.008*"man" + 0.007*"life" + 0.007*"guy" + 0.007*"way" + 0.006*"shit" + 0.006*"cause" + 0.005*"years"')]

In [15]:
# Let's try topics = 3
ldan = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.011*"thing" + 0.010*"day" + 0.008*"cause" + 0.008*"life" + 0.008*"man" + 0.007*"hes" + 0.007*"guy" + 0.007*"way" + 0.006*"women" + 0.006*"mom"'),
 (1,
  '0.010*"shit" + 0.009*"guy" + 0.007*"man" + 0.007*"thing" + 0.006*"way" + 0.006*"fuck" + 0.006*"hes" + 0.005*"life" + 0.005*"day" + 0.005*"guys"'),
 (2,
  '0.009*"day" + 0.009*"man" + 0.009*"kids" + 0.007*"shit" + 0.007*"thing" + 0.006*"cause" + 0.006*"gon" + 0.006*"hes" + 0.006*"way" + 0.005*"lot"')]

In [16]:
# Let's try 4 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.012*"thing" + 0.012*"day" + 0.011*"life" + 0.010*"hes" + 0.009*"man" + 0.007*"things" + 0.007*"joke" + 0.007*"way" + 0.007*"kids" + 0.006*"gon"'),
 (1,
  '0.010*"mom" + 0.008*"man" + 0.007*"guy" + 0.007*"thing" + 0.007*"shit" + 0.007*"guys" + 0.006*"hey" + 0.006*"shes" + 0.006*"women" + 0.006*"parents"'),
 (2,
  '0.010*"kids" + 0.007*"guy" + 0.007*"man" + 0.007*"way" + 0.006*"thing" + 0.005*"things" + 0.005*"day" + 0.005*"theyre" + 0.005*"lot" + 0.005*"years"'),
 (3,
  '0.010*"day" + 0.009*"thing" + 0.009*"guy" + 0.008*"man" + 0.007*"cause" + 0.007*"shit" + 0.007*"way" + 0.006*"fuck" + 0.006*"hes" + 0.006*"school"')]

## Topic Modeling - Attempt #3 (Nouns and Adjectives)

In [17]:
# Let's create a function to pull out nouns and adjectives from a string of text
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [18]:
# Apply the nouns function to the transcripts to filter only on nouns and adjectives
data_nouns_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns_adj

                                                transcript
ali      ladies gentlemen welcome stage ali wong hi wel...
anthony  thank san francisco thank good people surprise...
bill     right thank thank pleasure greater atlanta geo...
dave     whats name talk chappelle duke ellington schoo...
eric     sketch i evidence room man damn fool mushrooms...
george   november beacon theater new york city new york...
jim      ladies gentlemen welcome stage mr jim jefferie...
joe      ladies gentlemen joe fck san francisco thanks ...
john     boyish charm sharp wit former snl writer john ...
kenny    noise kenny sebastian oh god thank much mumbai...
louis    music lets lights lights thank much i i i nice...
mike     wow hey thanks hey seattle nice look crazy ins...
pete     ♪ old lady case ♪ ♪ shirt ♪ ♪ i win ♪ ♪ fuck c...
ricky    hello great thank fuck thank lovely welcome im...
taylor   welcome taylor tomlinson thank much thank much...
tom      time right ♪ ♪ bright city light ♪ ♪ turn litt...
trevor   potatoeszah zah potatoes baby house second yep...
whitney  good friend whitney cummings newark new jersey...

In [19]:
# Create a new document-term matrix using only nouns and adjectives, also remove common words with max_df
cvna = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names())
data_dtmna.index = data_nouns_adj.index
data_dtmna

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aaaaaa,aaaaaah,aaaaah,aaah,aah,abc,abcs,abetter,ability,abject,...,zero,zillion,ziploc,zoloft,zombie,zombies,zoo,zoom,zuko,éclair
ali,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bill,0,0,1,0,0,0,1,0,0,0,...,0,1,0,0,1,1,0,0,0,0
dave,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
eric,0,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
george,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
kenny,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
louis,0,0,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pete,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,0,0
taylor,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
tom,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
trevor,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
whitney,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [21]:
# Let's start with 2 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=2, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.005*"mom" + 0.004*"uh" + 0.004*"bro" + 0.004*"indian" + 0.003*"fuck" + 0.003*"kind" + 0.003*"curry" + 0.002*"ta" + 0.002*"high" + 0.002*"jenny"'),
 (1,
  '0.005*"fucking" + 0.005*"fuck" + 0.004*"joke" + 0.004*"mom" + 0.003*"kind" + 0.003*"different" + 0.003*"ta" + 0.003*"dick" + 0.003*"girl" + 0.003*"head"')]

In [22]:
# Let's try 3 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=3, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.007*"fuck" + 0.006*"mom" + 0.006*"fucking" + 0.004*"bro" + 0.004*"kind" + 0.003*"dick" + 0.003*"sex" + 0.002*"high" + 0.002*"head" + 0.002*"uh"'),
 (1,
  '0.005*"joke" + 0.005*"kind" + 0.004*"ta" + 0.004*"fck" + 0.004*"different" + 0.004*"mom" + 0.003*"girl" + 0.003*"jokes" + 0.003*"course" + 0.002*"ok"'),
 (2,
  '0.007*"indian" + 0.005*"curry" + 0.004*"fucking" + 0.004*"guns" + 0.004*"ass" + 0.003*"fuck" + 0.003*"uh" + 0.003*"order" + 0.003*"girls" + 0.003*"ta"')]

In [23]:
# Let's try 4 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.006*"indian" + 0.005*"joke" + 0.004*"curry" + 0.004*"ta" + 0.004*"funny" + 0.004*"news" + 0.003*"food" + 0.003*"order" + 0.002*"normal" + 0.002*"different"'),
 (1,
  '0.011*"fucking" + 0.009*"fuck" + 0.004*"gun" + 0.004*"kind" + 0.004*"guns" + 0.003*"head" + 0.003*"ass" + 0.003*"country" + 0.003*"son" + 0.003*"jesus"'),
 (2,
  '0.006*"mom" + 0.005*"sex" + 0.004*"ta" + 0.004*"older" + 0.004*"uh" + 0.003*"porn" + 0.003*"husband" + 0.003*"dick" + 0.003*"body" + 0.003*"different"'),
 (3,
  '0.007*"mom" + 0.005*"kind" + 0.004*"bro" + 0.004*"fck" + 0.004*"fuck" + 0.003*"joke" + 0.003*"friend" + 0.003*"dick" + 0.003*"high" + 0.003*"girl"')]

## Identify Topics in Each Document

Out of the 9 topic models we looked at, the nouns and adjectives, 4 topic one made the most sense. So let's pull that down here and run it through some more iterations to get more fine-tuned topics.

In [24]:
# Our final LDA model (for now)
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=80)
ldana.print_topics()

[(0,
  '0.007*"indian" + 0.006*"fuck" + 0.005*"curry" + 0.005*"fucking" + 0.004*"order" + 0.003*"uh" + 0.003*"fuckin" + 0.003*"trouble" + 0.003*"normal" + 0.003*"news"'),
 (1,
  '0.010*"joke" + 0.006*"fucking" + 0.005*"fuck" + 0.004*"guns" + 0.004*"jokes" + 0.004*"anthony" + 0.004*"funny" + 0.003*"party" + 0.003*"ass" + 0.003*"children"'),
 (2,
  '0.006*"bro" + 0.005*"kind" + 0.005*"jenny" + 0.005*"mom" + 0.004*"club" + 0.003*"door" + 0.003*"idea" + 0.003*"uh" + 0.003*"song" + 0.003*"accident"'),
 (3,
  '0.006*"mom" + 0.004*"fuck" + 0.004*"kind" + 0.004*"ta" + 0.004*"fucking" + 0.004*"different" + 0.004*"dick" + 0.003*"fck" + 0.003*"friend" + 0.003*"girl"')]

These four topics look pretty decent. Let's settle on these for now.
* Topic 0: food
* Topic 1: party
* Topic 2: friends
* Topic 3: profanity

In [25]:
# Let's take a look at which topics each transcript contains
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))

[(3, 'ali'),
 (1, 'anthony'),
 (0, 'bill'),
 (2, 'dave'),
 (3, 'eric'),
 (3, 'george'),
 (1, 'jim'),
 (3, 'joe'),
 (3, 'john'),
 (2, 'kenny'),
 (3, 'louis'),
 (2, 'mike'),
 (3, 'pete'),
 (1, 'ricky'),
 (3, 'taylor'),
 (3, 'tom'),
 (0, 'trevor'),
 (0, 'whitney')]

For a first pass of LDA, these kind of make sense to me, so we'll call it a day for now.
* Topic 0: food [Bill,Trevor,Whitney]
* Topic 1: party [Antony,Jim,Ricky]
* Topic 2: friends [Dave,Kenny,Mike]
* Topic 3: profanity [Ali,Eric,George,Joe,John,Louis,Pete,Taylor,Tom]

### Assignment:
1. Try further modifying the parameters of the topic models above and see if you can get better topics.
2. Create a new topic model that includes terms from a different [part of speech](https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html) and see if you can get better topics.

In [40]:
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people',
                  'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said', 'fuck', 'fucking','fck','sex']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)
cvna = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names())
data_dtmna.index = data_nouns_adj.index
data_dtmna

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aaaaaa,aaaaaah,aaaaah,aaah,aah,abc,abcs,abetter,ability,abject,...,zero,zillion,ziploc,zoloft,zombie,zombies,zoo,zoom,zuko,éclair
ali,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bill,0,0,1,0,0,0,1,0,0,0,...,0,1,0,0,1,1,0,0,0,0
dave,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
eric,0,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
george,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
kenny,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
louis,0,0,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pete,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,0,0
taylor,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
tom,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
trevor,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
whitney,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [46]:
ldana = models.LdaModel(corpus=corpusna, num_topics=8, id2word=id2wordna, passes=15, alpha='auto', eta='auto', chunksize=2000, minimum_probability=0.002)
ldana.print_topics()

[(0,
  '0.007*"mom" + 0.004*"friend" + 0.004*"clinton" + 0.004*"wife" + 0.004*"ta" + 0.004*"different" + 0.003*"dick" + 0.003*"hot" + 0.003*"cow" + 0.003*"girl"'),
 (1,
  '0.004*"theater" + 0.003*"ellington" + 0.003*"ta" + 0.003*"kind" + 0.003*"funny" + 0.003*"uh" + 0.003*"art" + 0.002*"live" + 0.002*"door" + 0.002*"idea"'),
 (2,
  '0.009*"mom" + 0.006*"joke" + 0.006*"indian" + 0.006*"bro" + 0.004*"uh" + 0.004*"curry" + 0.003*"ta" + 0.003*"anthony" + 0.003*"order" + 0.003*"news"'),
 (3,
  '0.004*"ayy" + 0.004*"kind" + 0.004*"dick" + 0.004*"gun" + 0.003*"head" + 0.003*"mom" + 0.003*"anybody" + 0.003*"plane" + 0.003*"jesus" + 0.003*"high"'),
 (4,
  '0.005*"kind" + 0.004*"dick" + 0.004*"girl" + 0.004*"different" + 0.003*"fcking" + 0.003*"stupid" + 0.003*"water" + 0.003*"country" + 0.003*"head" + 0.003*"mom"'),
 (5,
  '0.006*"guns" + 0.005*"ass" + 0.005*"girl" + 0.004*"girlfriend" + 0.004*"uh" + 0.004*"gun" + 0.004*"class" + 0.004*"business" + 0.004*"son" + 0.004*"girls"'),
 (6,
  '0.006*"ta" + 0.005*"husband" + 0.005*"ok" + 0.004*"uh" + 0.004*"mom" + 0.004*"pregnant" + 0.003*"kind" + 0.003*"ass" + 0.003*"different" + 0.003*"asian"'),
 (7,
  '0.005*"kind" + 0.005*"joke" + 0.004*"course" + 0.004*"jenny" + 0.003*"different" + 0.003*"nuts" + 0.003*"tit" + 0.003*"funny" + 0.003*"ta" + 0.003*"food"')]

In [47]:
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))

[(6, 'ali'),
 (2, 'anthony'),
 (3, 'bill'),
 (1, 'dave'),
 (2, 'eric'),
 (4, 'george'),
 (5, 'jim'),
 (4, 'joe'),
 (0, 'john'),
 (2, 'kenny'),
 (7, 'louis'),
 (7, 'mike'),
 (3, 'pete'),
 (7, 'ricky'),
 (0, 'taylor'),
 (0, 'tom'),
 (2, 'trevor'),
 (4, 'whitney')]

In [63]:
# Let's create a function to pull out nouns,verbs and adjectives from a string of text
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'VB' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [64]:
data_nouns_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns_adj

                                                transcript
ali      ladies gentlemen please welcome stage ali wong...
anthony  thank thank thank san francisco thank good be ...
bill     right thank thank thank thank are whats going ...
dave     whats name is talk chappelle delivered duke el...
eric     opening sketch i stole evidence room man legal...
george   recorded november beacon theater new york city...
jim      ladies gentlemen please welcome stage mr jim j...
joe      ladies gentlemen welcome joe rogan fck is goin...
john     armed boyish charm sharp wit former snl writer...
kenny    make noise kenny sebastian oh god thank much m...
louis    introfade music lets roll hold lights do light...
mike     wow hey thank thanks thank guys hey seattle ni...
pete     ♪ old lady case ♪ ♪ told straighten tuck shirt...
ricky    hello hello doing great thank wow calm shut fu...
taylor   please welcome taylor tomlinson thank much tha...
tom      time is right ♪ ♪ bright city light ♪ ♪ turn l...
trevor   potatoeszah zah potatoes baby baby i hear hous...
whitney  give good friend yours whitney cummings is new...

In [65]:
cvna = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names())
data_dtmna.index = data_nouns_adj.index
data_dtmna

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aaaaaa,aaaaaah,aaaaah,aaah,aah,abandon,abandoned,abc,abcs,abetter,...,zillion,ziploc,zoloft,zombie,zombies,zoning,zoo,zoom,zuko,éclair
ali,0,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bill,0,0,1,0,0,0,0,0,1,0,...,1,0,0,1,1,1,0,0,0,0
dave,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
eric,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
george,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
kenny,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
louis,0,0,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pete,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
taylor,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
tom,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
trevor,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
whitney,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [66]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [68]:
ldana = models.LdaModel(corpus=corpusna, num_topics=5,alpha='auto', eta='auto',chunksize=1000, minimum_probability=0.002,id2word=id2wordna, passes=15)
ldana.print_topics()

WARNING:gensim.models.ldamodel:updated prior not positive
WARNING:gensim.models.ldamodel:updated prior not positive
WARNING:gensim.models.ldamodel:updated prior not positive
WARNING:gensim.models.ldamodel:updated prior not positive
WARNING:gensim.models.ldamodel:updated prior not positive
WARNING:gensim.models.ldamodel:updated prior not positive
WARNING:gensim.models.ldamodel:updated prior not positive

[(0,
  '0.004*"joke" + 0.003*"mom" + 0.003*"die" + 0.003*"hell" + 0.002*"hed" + 0.002*"head" + 0.002*"sleep" + 0.002*"different" + 0.002*"bring" + 0.002*"kind"'),
 (1,
  '0.004*"mom" + 0.004*"fcking" + 0.004*"kind" + 0.003*"joke" + 0.003*"dick" + 0.003*"girl" + 0.003*"die" + 0.002*"different" + 0.002*"uh" + 0.002*"course"'),
 (2,
  '0.004*"uh" + 0.004*"mom" + 0.004*"says" + 0.003*"bro" + 0.003*"kind" + 0.003*"girl" + 0.002*"ass" + 0.002*"friend" + 0.002*"jenny" + 0.002*"girls"'),
 (3,
  '0.004*"indian" + 0.003*"curry" + 0.003*"kind" + 0.002*"aint" + 0.002*"head" + 0.002*"uh" + 0.002*"food" + 0.002*"country" + 0.002*"order" + 0.002*"kill"'),
 (4,
  '0.003*"mom" + 0.003*"uh" + 0.003*"husband" + 0.003*"ok" + 0.003*"kind" + 0.003*"die" + 0.002*"pregnant" + 0.002*"different" + 0.002*"ass" + 0.002*"says"')]

In [69]:
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))

[(4, 'ali'),
 (1, 'anthony'),
 (0, 'bill'),
 (3, 'dave'),
 (2, 'eric'),
 (3, 'george'),
 (2, 'jim'),
 (1, 'joe'),
 (1, 'john'),
 (2, 'kenny'),
 (1, 'louis'),
 (2, 'mike'),
 (1, 'pete'),
 (0, 'ricky'),
 (0, 'taylor'),
 (2, 'tom'),
 (3, 'trevor'),
 (1, 'whitney')]